## EDUNET FOUNDATION - Self-Practice Exercise Notebook Solutions

### LAB 8 - Implementing Numpy Concepts in Python

**Problem 1:** Write a NumPy program to test whether none of the elements of a given array are zero.

In [1]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


**Problem 2:** Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [2]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Problem 3:** Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [3]:
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-0.53335567  0.61522366 -0.8050965   0.14968149 -0.97719    -0.10663548
 -0.52760673  0.64251073  0.05698474  1.16536732  1.42087996 -0.73988586
  0.07338494  0.35109644  0.70637165]


**Problem 4:** Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [4]:
import numpy as np 
np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1)

[[201.6908267  200.37467631 200.68394275 195.51750123]
 [197.92478992 201.07066048 201.79714021 198.1282331 ]
 [200.96238963 200.77744291 200.61875865 199.05613894]
 [198.48492638 198.38860811 197.55239946 200.47003621]
 [199.91545839 202.99877319 202.01069857 200.77735483]
 [199.67739161 193.89831807 202.14273593 202.54951299]
 [199.53450969 199.7512602  199.79145727 202.97687757]
 [200.24634413 196.04606934 198.30611253 197.88701546]
 [201.78450912 203.94032834 198.21152803 196.91446071]
 [201.0082481  197.03285104 200.63052763 197.82590294]]


**Problem 5:** Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [5]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


**Problem 6:** Write a NumPy program to swap rows and columns of a given array in reverse order.

In [6]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


**Problem 7:** Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [8]:
import numpy as np 
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]


**Problem 8:** Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**Problem 9:** Write a NumPy program to create a 3x3x3 array with random values. Expected Output:

[[[ 0.48941799 0.58722213 0.43453926] [ 0.94497547 0.81081709 0.1510409 ] [ 0.66657127 0.29494755 0.48047144]] [[ 0.02287253 0.95232614 0.32264936] [ 0.67009741 0.25458304 0.16290913] [ 0.15520198 0.86826529 0.9679322 ]] [[ 0.13503103 0.02042211 0.24683897] [ 0.97852158 0.22374748 0.10798856] [ 0.62032646 0.5893892 0.16958144]]]

In [10]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.82582358 0.15639172 0.73430052]
  [0.40864343 0.7786879  0.80397057]
  [0.78607144 0.59228702 0.6644892 ]]

 [[0.64656729 0.42563648 0.51356833]
  [0.50125784 0.03708381 0.7081161 ]
  [0.6204306  0.77780853 0.45940947]]

 [[0.37980555 0.2918922  0.55722886]
  [0.0841636  0.63128167 0.94457049]
  [0.89123753 0.87858258 0.34475163]]]


**Problem 10:** Write a Python program to find the maximum and minimum value of a given flattened array.

In [11]:
import numpy as np
a = np.arange(4).reshape((2,2))
print("Original flattened array:")
print(a)
print("Maximum value of the above flattened array:")
print(np.amax(a))
print("Minimum value of the above flattened array:")
print(np.amin(a))

Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array:
3
Minimum value of the above flattened array:
0


**Problem 11:** Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
Expected Output: Add: 5.0 Subtract: -3.0 Multiply: 4.0 Divide: 0.25

In [13]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


**Problem 12:** Write a NumPy program to get the powers of an array values element-wise. Note: First array elements raised to powers from second array          
Expected Output: Original array [0 1 2 3 4 5 6] First array elements raised to powers from second array, element-wise: [ 0 1 8 27 64 125 216]

In [14]:
import numpy as np
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


**Problem 13:** Create a Python project to guess a number that has randomly selected.

In [16]:
import random
number=random.randrange(0,100)
guessCheck="wrong"
print("Welcome to Number Guess")

while guessCheck=="wrong":
	response=int(input("Please input a number between 0 and 100:"))
	try:
		val=int(response)
	except ValueError:
		print("This is not a valid integer. Please try again")
		continue
	val=int (response)
	if val<number:
		print("This is lower than actual number. Please try again.")
	elif val>number:
		print("This is higher than actual number. Please try again.")
	else:
		print("This is the correct number")
		guessCheck="correct"

print("Thank you for playing Number Guess. See you again")

Welcome to Number Guess
Please input a number between 0 and 100:60
This is lower than actual number. Please try again.
Please input a number between 0 and 100:70
This is lower than actual number. Please try again.
Please input a number between 0 and 100:80
This is lower than actual number. Please try again.
Please input a number between 0 and 100:90
This is higher than actual number. Please try again.
Please input a number between 0 and 100:85
This is lower than actual number. Please try again.
Please input a number between 0 and 100:88
This is higher than actual number. Please try again.
Please input a number between 0 and 100:86
This is the correct number
Thank you for playing Number Guess. See you again


**Problem 14:** Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
Expected Output: Original array: [[ 1. 1. 1. 1. 1.] ................... [ 1. 1. 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] ................... [ 1. 1. 1. 1. 1.]]

In [17]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Problem 15:** Write a NumPy program to append values to the end of an array.
Expected Output: Original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [18]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
